title: Kit d'intervention rapide
description: Kit d'intervention
author: Société numérique
twitter:
  username: missionsonum
facebook:
  publisher: MissionSoNum
logo: /images/logo.png
social:
  links:
    - https://twitter.com/missionsonum
    - https://www.facebook.com/MissionSoNum
    - https://www.linkedin.com/company/18465343/
    - https://github.com/SocieteNumerique
google_site_verification:
lang: fr_FR

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
